// ==================== 48 强球队阵容数据（Phase 3 数据源，单一事实来源） ====================
// 从 2026.tsx 迁移至此，供引擎派生攻防评分（C1）。UI 也从此导入，消除重复。
// 球员质量信号 = 所属俱乐部级别（见 clubs.ts 的分级），按位置聚合为球队 attack/defense。

export type Pos = 'GK' | 'DF' | 'MF' | 'FW';

export interface SquadPlayer {
  name: string;
  pos: Pos;
  num: number;
  club: string;
}

export interface Squad {
  coach: string;
  players: SquadPlayer[];
}

export const teamSquads: Record<string, Squad> = {
  '墨西哥': { coach: '哈维尔·阿吉雷', players: [
    { name: 'Guillermo Ochoa', pos: 'GK', num: 13, club: '萨勒尼塔纳' },
    { name: 'Jorge Sanchez', pos: 'DF', num: 2, club: '阿贾克斯' },
    { name: 'Cesar Montes', pos: 'DF', num: 3, club: '莫斯科火车头' },
    { name: 'Edson Alvarez', pos: 'MF', num: 4, club: '西汉姆' },
    { name: 'Luis Romo', pos: 'MF', num: 6, club: '蓝十字' },
    { name: 'Hirving Lozano', pos: 'FW', num: 11, club: 'PSV' },
    { name: 'Santiago Gimenez', pos: 'FW', num: 9, club: '费耶诺德' },
    { name: 'Uriel Antuna', pos: 'FW', num: 7, club: '瓜达拉哈拉' },
    { name: 'Alexis Vega', pos: 'FW', num: 10, club: '蓝十字' },
    { name: 'Julian Quiñones', pos: 'FW', num: 19, club: '阿尔赖扬' },
    { name: 'Raul Jimenez', pos: 'FW', num: 20, club: '富勒姆' },
  ]},
  '南非': { coach: '雨果·布罗斯', players: [
    { name: 'Ronwen Williams', pos: 'GK', num: 1, club: '马梅洛迪日落' },
    { name: 'Siyanda Xulu', pos: 'DF', num: 2, club: 'HTT GALAXY' },
    { name: 'Mothobi Mvala', pos: 'DF', num: 4, club: '马梅洛迪日落' },
    { name: 'Teboho Mokoena', pos: 'MF', num: 6, club: '马梅洛迪日落' },
    { name: 'Percy Tau', pos: 'FW', num: 10, club: '阿尔阿赫利' },
    { name: 'Lyle Foster', pos: 'FW', num: 9, club: '伯恩利' },
    { name: 'Evidence Makgopa', pos: 'FW', num: 11, club: '奥兰多海盗' },
    { name: 'Themba Zwane', pos: 'MF', num: 7, club: '马梅洛迪日落' },
    { name: 'Relebohile Mofokeng', pos: 'FW', num: 18, club: '奥兰多海盗' },
  ]},
  '韩国': { coach: '洪明甫', players: [
    { name: 'Kim Seung-gyu', pos: 'GK', num: 1, club: '阿尔沙巴布' },
    { name: 'Kim Min-jae', pos: 'DF', num: 4, club: '拜仁慕尼黑' },
    { name: 'Kim Jin-su', pos: 'DF', num: 3, club: '全北现代' },
    { name: 'Lee Kang-in', pos: 'MF', num: 10, club: '巴黎圣日耳曼' },
    { name: 'Hwang Hee-chan', pos: 'FW', num: 11, club: '狼队' },
    { name: 'Son Heung-min', pos: 'FW', num: 7, club: '热刺' },
    { name: 'Hwang Ui-jo', pos: 'FW', num: 9, club: '阿拉尼亚体育' },
    { name: 'Paik Seung-ho', pos: 'MF', num: 8, club: '伯明翰' },
    { name: 'Cho Gue-sung', pos: 'FW', num: 19, club: '米特威尔兰' },
  ]},
  '捷克': { coach: '伊万·哈谢克', players: [
    { name: 'Jindrich Stanek', pos: 'GK', num: 1, club: '比尔森胜利' },
    { name: 'Vladimir Coufal', pos: 'DF', num: 2, club: '西汉姆' },
    { name: 'David Zima', pos: 'DF', num: 3, club: '布拉格斯拉维亚' },
    { name: 'Tomas Soucek', pos: 'MF', num: 4, club: '西汉姆' },
    { name: 'Antonin Barak', pos: 'MF', num: 8, club: '佛罗伦萨' },
    { name: 'Patrik Schick', pos: 'FW', num: 10, club: '勒沃库森' },
    { name: 'Adam Hlozek', pos: 'FW', num: 7, club: '勒沃库森' },
    { name: 'Vaclav Cerny', pos: 'FW', num: 11, club: '格拉斯哥流浪者' },
    { name: 'Lukas Provod', pos: 'MF', num: 14, club: '布拉格斯拉维亚' },
  ]},
  '加拿大': { coach: '杰西·马希', players: [
    { name: 'Alphonso Davies', pos: 'DF', num: 19, club: '拜仁慕尼黑' },
    { name: 'Jonathan David', pos: 'FW', num: 9, club: '尤文图斯' },
    { name: 'Stephen Eustaquio', pos: 'MF', num: 7, club: '波尔图' },
    { name: 'Tajon Buchanan', pos: 'FW', num: 17, club: '比利亚雷亚尔' },
    { name: 'Cyle Larin', pos: 'FW', num: 11, club: '马略卡' },
    { name: 'Ismael Kone', pos: 'MF', num: 14, club: '马赛' },
    { name: 'Dayne St. Clair', pos: 'GK', num: 1, club: '明尼苏达联' },
    { name: 'Alistair Johnston', pos: 'DF', num: 2, club: '凯尔特人' },
    { name: 'Liam Millar', pos: 'FW', num: 20, club: '普利茅斯' },
  ]},
  '波黑': { coach: '谢尔盖·巴尔巴雷兹', players: [
    { name: 'Asmir Begovic', pos: 'GK', num: 1, club: '莱斯特城' },
    { name: 'Sead Kolasinac', pos: 'DF', num: 3, club: '亚特兰大' },
    { name: 'Anel Ahmedhodzic', pos: 'DF', num: 4, club: '谢菲尔德联' },
    { name: 'Miralem Pjanic', pos: 'MF', num: 10, club: '中央陆军' },
    { name: 'Edin Visca', pos: 'FW', num: 7, club: '巴萨克赛尔' },
    { name: 'Rade Krunic', pos: 'MF', num: 8, club: '费内巴切' },
    { name: 'Benjamin Tahirovic', pos: 'MF', num: 14, club: '阿贾克斯' },
    { name: 'Said Hamulic', pos: 'FW', num: 9, club: '图卢兹' },
  ]},
  '卡塔尔': { coach: '廷廷·马克斯', players: [
    { name: 'Saad Al-Sheeb', pos: 'GK', num: 1, club: '萨德' },
    { name: 'Pedro Miguel', pos: 'DF', num: 2, club: '萨德' },
    { name: 'Boualem Khoukhi', pos: 'DF', num: 3, club: '萨德' },
    { name: 'Karim Boudiaf', pos: 'MF', num: 6, club: '杜海勒' },
    { name: 'Akram Afif', pos: 'FW', num: 10, club: '萨德' },
    { name: 'Almoez Ali', pos: 'FW', num: 9, club: '杜海勒' },
    { name: 'Hassan Al-Haydos', pos: 'FW', num: 7, club: '萨德' },
    { name: 'Ahmed Alaaeldin', pos: 'FW', num: 11, club: '加拉法' },
  ]},
  '瑞士': { coach: '穆拉特·雅金', players: [
    { name: 'Yann Sommer', pos: 'GK', num: 1, club: '拜仁慕尼黑' },
    { name: 'Manuel Akanji', pos: 'DF', num: 5, club: '曼城' },
    { name: 'Ricardo Rodriguez', pos: 'DF', num: 13, club: '贝蒂斯' },
    { name: 'Granit Xhaka', pos: 'MF', num: 10, club: '勒沃库森' },
    { name: 'Xherdan Shaqiri', pos: 'MF', num: 7, club: '芝加哥火焰' },
    { name: 'Ruben Vargas', pos: 'FW', num: 11, club: '柏林联合' },
    { name: 'Breel Embolo', pos: 'FW', num: 9, club: '摩纳哥' },
    { name: 'Dan Ndoye', pos: 'FW', num: 17, club: '博洛尼亚' },
    { name: 'Denis Zakaria', pos: 'MF', num: 8, club: '摩纳哥' },
    { name: 'Silvan Widmer', pos: 'DF', num: 2, club: '美因茨' },
  ]},
  '巴西': { coach: '卡洛·安切洛蒂', players: [
    { name: 'Alisson', pos: 'GK', num: 1, club: '利物浦' },
    { name: 'Marquinhos', pos: 'DF', num: 3, club: '巴黎圣日耳曼' },
    { name: 'Gabriel Magalhaes', pos: 'DF', num: 4, club: '阿森纳' },
    { name: 'Danilo', pos: 'DF', num: 2, club: '弗拉门戈' },
    { name: 'Bruno Guimaraes', pos: 'MF', num: 8, club: '纽卡斯尔' },
    { name: 'Casemiro', pos: 'MF', num: 5, club: '曼联' },
    { name: 'Raphinha', pos: 'FW', num: 11, club: '巴塞罗那' },
    { name: 'Rodrygo', pos: 'FW', num: 7, club: '皇家马德里' },
    { name: 'Endrick', pos: 'FW', num: 9, club: '皇家马德里' },
    { name: 'Vinicius Jr', pos: 'FW', num: 10, club: '皇家马德里' },
    { name: 'Estevao Willian', pos: 'FW', num: 17, club: '切尔西' },
  ]},
  '摩洛哥': { coach: '穆罕默德·瓦赫比', players: [
    { name: 'Yassine Bounou', pos: 'GK', num: 1, club: '利雅得新月' },
    { name: 'Achraf Hakimi', pos: 'DF', num: 2, club: '巴黎圣日耳曼' },
    { name: 'Noussair Mazraoui', pos: 'DF', num: 3, club: '曼联' },
    { name: 'Romain Saiss', pos: 'DF', num: 6, club: '贝西克塔斯' },
    { name: 'Brahim Diaz', pos: 'FW', num: 10, club: '皇家马德里' },
    { name: 'Azzedine Ounahi', pos: 'MF', num: 8, club: '马赛' },
    { name: 'Sofyan Amrabat', pos: 'MF', num: 4, club: '费内巴切' },
    { name: 'Youssef En-Nesyri', pos: 'FW', num: 19, club: '费内巴切' },
    { name: 'Hakim Ziyech', pos: 'MF', num: 7, club: '加拉塔萨雷' },
    { name: 'Nayef Aguerd', pos: 'DF', num: 5, club: '皇家社会' },
  ]},
  '海地': { coach: '塞巴斯蒂安·米涅', players: [
    { name: 'Johny Placide', pos: 'GK', num: 1, club: '巴斯蒂亚' },
    { name: 'Carlens Arcus', pos: 'DF', num: 2, club: '昂热' },
    { name: 'Hannes Delcroix', pos: 'DF', num: 5, club: '伯恩利' },
    { name: 'Duckens Nazon', pos: 'FW', num: 9, club: '查韦斯' },
    { name: 'Frantzdy Pierrot', pos: 'FW', num: 11, club: '根特' },
    { name: 'Jean-Kevin Duverne', pos: 'DF', num: 22, club: '波鸿' },
    { name: 'Bryan Labissiere', pos: 'MF', num: 8, club: '色当' },
    { name: 'Wilde-Donald Guerrier', pos: 'MF', num: 10, club: '卡拉巴赫' },
  ]},
  '苏格兰': { coach: '史蒂夫·克拉克', players: [
    { name: 'Craig Gordon', pos: 'GK', num: 1, club: '哈茨' },
    { name: 'Andy Robertson', pos: 'DF', num: 2, club: '利物浦' },
    { name: 'Kieran Tierney', pos: 'DF', num: 3, club: '阿森纳' },
    { name: 'Scott McTominay', pos: 'MF', num: 4, club: '那不勒斯' },
    { name: 'John McGinn', pos: 'MF', num: 6, club: '阿斯顿维拉' },
    { name: 'Billy Gilmour', pos: 'MF', num: 8, club: '那不勒斯' },
    { name: 'Lewis Ferguson', pos: 'MF', num: 10, club: '博洛尼亚' },
    { name: 'Lyndon Dykes', pos: 'FW', num: 9, club: '女王公园巡游者' },
    { name: 'Ben Doak', pos: 'FW', num: 11, club: '利物浦' },
    { name: 'Lawrence Shankland', pos: 'FW', num: 7, club: '哈茨' },
  ]},
  '美国': { coach: '毛里西奥·波切蒂诺', players: [
    { name: 'Matt Turner', pos: 'GK', num: 1, club: '水晶宫' },
    { name: 'Antonee Robinson', pos: 'DF', num: 2, club: '富勒姆' },
    { name: 'Tim Ream', pos: 'DF', num: 4, club: '夏洛特FC' },
    { name: 'Weston McKennie', pos: 'MF', num: 8, club: '尤文图斯' },
    { name: 'Tyler Adams', pos: 'MF', num: 6, club: '伯恩茅斯' },
    { name: 'Christian Pulisic', pos: 'FW', num: 10, club: 'AC米兰' },
    { name: 'Giovanni Reyna', pos: 'MF', num: 7, club: '多特蒙德' },
    { name: 'Folarin Balogun', pos: 'FW', num: 9, club: '摩纳哥' },
    { name: 'Timothy Weah', pos: 'FW', num: 11, club: '尤文图斯' },
    { name: 'Yunus Musah', pos: 'MF', num: 14, club: 'AC米兰' },
  ]},
  '巴拉圭': { coach: '古斯塔沃·阿尔法罗', players: [
    { name: 'Anthony Silva', pos: 'GK', num: 1, club: '波特诺山丘' },
    { name: 'Gustavo Gomez', pos: 'DF', num: 3, club: '帕尔梅拉斯' },
    { name: 'Fabian Balbuena', pos: 'DF', num: 4, club: '迪拜青年' },
    { name: 'Miguel Almiron', pos: 'MF', num: 10, club: '纽卡斯尔' },
    { name: 'Mathias Villasanti', pos: 'MF', num: 8, club: '格雷米奥' },
    { name: 'Omar Alderete', pos: 'DF', num: 5, club: '赫塔菲' },
    { name: 'Antonio Sanabria', pos: 'FW', num: 9, club: '都灵' },
    { name: 'Julio Enciso', pos: 'FW', num: 11, club: '布莱顿' },
    { name: 'Adam Bareiro', pos: 'FW', num: 7, club: '蒙特雷' },
  ]},
  '澳大利亚': { coach: '托尼·波波维奇', players: [
    { name: 'Mat Ryan', pos: 'GK', num: 1, club: '罗马' },
    { name: 'Harry Souttar', pos: 'DF', num: 4, club: '谢菲尔德联' },
    { name: 'Aziz Behich', pos: 'DF', num: 3, club: '墨尔本城' },
    { name: 'Jackson Irvine', pos: 'MF', num: 8, club: '圣保利' },
    { name: "Aiden O'Neill", pos: 'MF', num: 6, club: '标准列日' },
    { name: 'Mathew Leckie', pos: 'FW', num: 7, club: '墨尔本城' },
    { name: 'Mitchell Duke', pos: 'FW', num: 9, club: '町田泽维亚' },
    { name: 'Craig Goodwin', pos: 'FW', num: 11, club: '阿尔韦达' },
    { name: 'Kusini Yengi', pos: 'FW', num: 15, club: '朴茨茅斯' },
  ]},
  '土耳其': { coach: '温琴佐·蒙特拉', players: [
    { name: 'Altay Bayindir', pos: 'GK', num: 12, club: '曼联' },
    { name: 'Mert Gunok', pos: 'GK', num: 1, club: '费内巴切' },
    { name: 'Zeki Celik', pos: 'DF', num: 2, club: '罗马' },
    { name: 'Merih Demiral', pos: 'DF', num: 4, club: '吉达联合' },
    { name: 'Hakan Calhanoglu', pos: 'MF', num: 10, club: '国际米兰' },
    { name: 'Arda Guler', pos: 'MF', num: 8, club: '皇家马德里' },
    { name: 'Kenan Yildiz', pos: 'FW', num: 7, club: '尤文图斯' },
    { name: 'Irfan Can Kahveci', pos: 'MF', num: 14, club: '费内巴切' },
    { name: 'Baris Alper Yilmaz', pos: 'FW', num: 11, club: '加拉塔萨雷' },
    { name: 'Cengiz Under', pos: 'FW', num: 9, club: '洛杉矶FC' },
  ]},
  '德国': { coach: '尤利安·纳格尔斯曼', players: [
    { name: 'Manuel Neuer', pos: 'GK', num: 1, club: '拜仁慕尼黑' },
    { name: 'Antonio Rudiger', pos: 'DF', num: 2, club: '皇家马德里' },
    { name: 'Joshua Kimmich', pos: 'MF', num: 6, club: '拜仁慕尼黑' },
    { name: 'Jamal Musiala', pos: 'MF', num: 10, club: '拜仁慕尼黑' },
    { name: 'Florian Wirtz', pos: 'MF', num: 17, club: '勒沃库森' },
    { name: 'Kai Havertz', pos: 'FW', num: 7, club: '阿森纳' },
    { name: 'Nico Schlotterbeck', pos: 'DF', num: 15, club: '多特蒙德' },
    { name: 'Ilkay Gundogan', pos: 'MF', num: 8, club: '曼城' },
    { name: 'Leroy Sane', pos: 'FW', num: 11, club: '拜仁慕尼黑' },
    { name: 'Niclas Fullkrug', pos: 'FW', num: 9, club: '西汉姆' },
    { name: 'Waldemar Anton', pos: 'DF', num: 3, club: '多特蒙德' },
  ]},
  '库拉索': { coach: '迪克·艾德沃卡特', players: [
    { name: 'Eloy Room', pos: 'GK', num: 1, club: '费耶诺德' },
    { name: 'Leandro Bacuna', pos: 'MF', num: 10, club: '格拉斯哥流浪者' },
    { name: 'Cuco Martina', pos: 'DF', num: 2, club: '布雷达' },
    { name: 'Jurgen Locadia', pos: 'FW', num: 9, club: '阿马萨斯' },
    { name: 'Gastón Guridi', pos: 'FW', num: 7, club: '班菲尔德' },
    { name: 'Rangelo Janga', pos: 'FW', num: 11, club: '沃鲁斯拉' },
    { name: 'Kenith Guiton', pos: 'MF', num: 8, club: '埃蒙' },
  ]},
  '科特迪瓦': { coach: '埃默斯·法埃', players: [
    { name: 'Yahia Fofana', pos: 'GK', num: 1, club: '里泽斯堡' },
    { name: 'Evan Ndicka', pos: 'DF', num: 21, club: '罗马' },
    { name: 'Wilfried Singo', pos: 'DF', num: 2, club: '摩纳哥' },
    { name: 'Ousmane Diomande', pos: 'DF', num: 4, club: '里斯本竞技' },
    { name: 'Franck Kessie', pos: 'MF', num: 8, club: '吉达联合' },
    { name: 'Seko Fofana', pos: 'MF', num: 10, club: '雷恩' },
    { name: 'Simon Adingra', pos: 'FW', num: 11, club: '摩纳哥' },
    { name: 'Sebastien Haller', pos: 'FW', num: 9, club: '多特蒙德' },
    { name: 'Guela Doue', pos: 'DF', num: 17, club: '雷恩' },
    { name: 'Jean-Philippe Mateta', pos: 'FW', num: 14, club: '水晶宫' },
  ]},
  '厄瓜多尔': { coach: '塞巴斯蒂安·贝卡塞切', players: [
    { name: 'Hernan Galindez', pos: 'GK', num: 1, club: '飓风' },
    { name: 'Piero Hincapie', pos: 'DF', num: 3, club: '勒沃库森' },
    { name: 'Willian Pacho', pos: 'DF', num: 6, club: '法兰克福' },
    { name: 'Moises Caicedo', pos: 'MF', num: 23, club: '切尔西' },
    { name: 'Kendry Paez', pos: 'MF', num: 10, club: '切尔西' },
    { name: 'Enner Valencia', pos: 'FW', num: 9, club: '国际米兰' },
    { name: 'Gonzalo Plata', pos: 'FW', num: 7, club: '阿尔萨德' },
    { name: 'Angel Mena', pos: 'FW', num: 11, club: '莱昂' },
    { name: 'Alan Franco', pos: 'MF', num: 21, club: '巴伊亚' },
  ]},
  '荷兰': { coach: '罗纳德·科曼', players: [
    { name: 'Bart Verbruggen', pos: 'GK', num: 1, club: '布莱顿' },
    { name: 'Virgil van Dijk', pos: 'DF', num: 4, club: '利物浦' },
    { name: 'Jurrien Timber', pos: 'DF', num: 2, club: '阿森纳' },
    { name: 'Nathan Ake', pos: 'DF', num: 5, club: '曼城' },
    { name: 'Frenkie de Jong', pos: 'MF', num: 8, club: '巴塞罗那' },
    { name: 'Xavi Simons', pos: 'MF', num: 10, club: '莱比锡' },
    { name: 'Cody Gakpo', pos: 'FW', num: 7, club: '利物浦' },
    { name: 'Memphis Depay', pos: 'FW', num: 9, club: '科林蒂安' },
    { name: 'Donyell Malen', pos: 'FW', num: 11, club: '多特蒙德' },
    { name: 'Marten de Roon', pos: 'MF', num: 3, club: '亚特兰大' },
  ]},
  '日本': { coach: '森保一', players: [
    { name: 'Zion Suzuki', pos: 'GK', num: 12, club: '帕尔马' },
    { name: 'Ko Itakura', pos: 'DF', num: 3, club: '门兴' },
    { name: 'Yuto Nagatomo', pos: 'DF', num: 2, club: 'FC东京' },
    { name: 'Wataru Endo', pos: 'MF', num: 6, club: '利物浦' },
    { name: 'Takefusa Kubo', pos: 'MF', num: 10, club: '皇家社会' },
    { name: 'Kaoru Mitoma', pos: 'FW', num: 7, club: '布莱顿' },
    { name: 'Ritsu Doan', pos: 'FW', num: 11, club: '弗赖堡' },
    { name: 'Daizen Maeda', pos: 'FW', num: 9, club: '凯尔特人' },
    { name: 'Ayase Ueda', pos: 'FW', num: 20, club: '费耶诺德' },
    { name: 'Hidemasa Morita', pos: 'MF', num: 8, club: '里斯本竞技' },
  ]},
  '瑞典': { coach: '容·达尔·托马森', players: [
    { name: 'Robin Olsen', pos: 'GK', num: 1, club: '阿斯顿维拉' },
    { name: 'Victor Lindelof', pos: 'DF', num: 3, club: '曼联' },
    { name: 'Isak Hien', pos: 'DF', num: 4, club: '亚特兰大' },
    { name: 'Emil Forsberg', pos: 'MF', num: 10, club: '纽约红牛' },
    { name: 'Dejan Kulusevski', pos: 'MF', num: 7, club: '热刺' },
    { name: 'Alexander Isak', pos: 'FW', num: 9, club: '纽卡斯尔' },
    { name: 'Viktor Gyokeres', pos: 'FW', num: 11, club: '里斯本竞技' },
    { name: 'Lucas Walhstrom', pos: 'MF', num: 8, club: '哈马比' },
    { name: 'Ludvig Augustinsson', pos: 'DF', num: 2, club: '塞维利亚' },
  ]},
  '突尼斯': { coach: '萨阿德·布萨迪', players: [
    { name: 'Aymen Dahmen', pos: 'GK', num: 1, club: '斯法克西恩' },
    { name: 'Ali Maaloul', pos: 'DF', num: 2, club: '阿尔阿赫利' },
    { name: 'Montassar Talbi', pos: 'DF', num: 4, club: '洛里昂' },
    { name: 'Ellyes Skhiri', pos: 'MF', num: 6, club: '法兰克福' },
    { name: 'Ferjani Sassi', pos: 'MF', num: 8, club: '杜海勒' },
    { name: 'Youssef Msakni', pos: 'FW', num: 7, club: '阿尔阿拉比' },
    { name: 'Wahbi Khazri', pos: 'FW', num: 10, club: '蒙彼利埃' },
    { name: 'Issam Jebali', pos: 'FW', num: 9, club: '沃鲁斯拉' },
    { name: 'Hannibal Mejbri', pos: 'MF', num: 11, club: '伯恩利' },
  ]},
  '比利时': { coach: '多梅尼科·特德斯科', players: [
    { name: 'Thibaut Courtois', pos: 'GK', num: 1, club: '皇家马德里' },
    { name: 'Jan Vertonghen', pos: 'DF', num: 5, club: '梅赫伦' },
    { name: 'Arthur Theate', pos: 'DF', num: 3, club: '法兰克福' },
    { name: 'Kevin De Bruyne', pos: 'MF', num: 10, club: '曼城' },
    { name: 'Youri Tielemans', pos: 'MF', num: 8, club: '阿斯顿维拉' },
    { name: 'Amadou Onana', pos: 'MF', num: 6, club: '阿斯顿维拉' },
    { name: 'Romelu Lukaku', pos: 'FW', num: 9, club: '切尔西' },
    { name: 'Leandro Trossard', pos: 'FW', num: 11, club: '阿森纳' },
    { name: 'Jeremy Doku', pos: 'FW', num: 7, club: '曼城' },
    { name: 'Charles De Ketelaere', pos: 'FW', num: 17, club: '亚特兰大' },
  ]},
  '埃及': { coach: '鲁伊·维多利亚', players: [
    { name: 'Mohamed El Shenawy', pos: 'GK', num: 1, club: '阿尔阿赫利' },
    { name: 'Ahmed Hegazi', pos: 'DF', num: 4, club: '伊蒂哈德' },
    { name: 'Omar Marmoush', pos: 'FW', num: 7, club: '曼城' },
    { name: 'Mohamed Salah', pos: 'FW', num: 10, club: '利物浦' },
    { name: 'Trezequet', pos: 'MF', num: 8, club: '特拉布宗体育' },
    { name: 'Mostafa Mohamed', pos: 'FW', num: 9, club: '南特' },
    { name: 'Hussien El Shahat', pos: 'FW', num: 11, club: '阿尔阿赫利' },
    { name: 'Ahmed Fathi', pos: 'DF', num: 2, club: '金字塔' },
  ]},
  '伊朗': { coach: '阿米尔·加莱诺伊', players: [
    { name: 'Alireza Beiranvand', pos: 'GK', num: 1, club: '波斯波利斯' },
    { name: 'Milad Mohammadi', pos: 'DF', num: 2, club: 'AEK雅典' },
    { name: 'Shoja Khalilzadeh', pos: 'DF', num: 4, club: '波斯波利斯' },
    { name: 'Saman Ghoddos', pos: 'MF', num: 8, club: '布伦特福德' },
    { name: 'Sardar Azmoun', pos: 'FW', num: 9, club: '迪拜祈祷' },
    { name: 'Mehdi Taremi', pos: 'FW', num: 10, club: '国际米兰' },
    { name: 'Alireza Jahanbakhsh', pos: 'FW', num: 7, club: '费耶诺德' },
    { name: 'Ramin Rezaeian', pos: 'MF', num: 11, club: '塞帕罕' },
  ]},
  '新西兰': { coach: '达伦·巴兹利', players: [
    { name: 'Stefan Marinovic', pos: 'GK', num: 1, club: '惠灵顿凤凰' },
    { name: 'Winston Reid', pos: 'DF', num: 4, club: '惠灵顿凤凰' },
    { name: 'Liberato Cacace', pos: 'DF', num: 3, club: '恩波利' },
    { name: 'Chris Wood', pos: 'FW', num: 9, club: '诺丁汉森林' },
    { name: 'Marco Rojas', pos: 'FW', num: 7, club: '科洛科洛' },
    { name: 'Sarpreet Singh', pos: 'MF', num: 10, club: '不来梅' },
    { name: 'Joe Champness', pos: 'FW', num: 11, club: '阿德莱德联' },
  ]},
  '西班牙': { coach: '路易斯·德拉富恩特', players: [
    { name: 'David Raya', pos: 'GK', num: 1, club: '阿森纳' },
    { name: 'Marc Cucurella', pos: 'DF', num: 2, club: '切尔西' },
    { name: 'Aymeric Laporte', pos: 'DF', num: 14, club: '利雅得胜利' },
    { name: 'Pau Cubarsi', pos: 'DF', num: 4, club: '巴塞罗那' },
    { name: 'Rodri', pos: 'MF', num: 16, club: '曼城' },
    { name: 'Pedri', pos: 'MF', num: 8, club: '巴塞罗那' },
    { name: 'Fabian Ruiz', pos: 'MF', num: 6, club: '巴黎圣日耳曼' },
    { name: 'Lamine Yamal', pos: 'FW', num: 19, club: '巴塞罗那' },
    { name: 'Nico Williams', pos: 'FW', num: 11, club: '毕尔巴鄂竞技' },
    { name: 'Alvaro Morata', pos: 'FW', num: 7, club: '科莫' },
    { name: 'Mikel Oyarzabal', pos: 'FW', num: 9, club: '皇家社会' },
  ]},
  '佛得角': { coach: '布卜卡·科布', players: [
    { name: 'Vozinha', pos: 'GK', num: 1, club: '阿马多拉' },
    { name: 'Steven Fortes', pos: 'DF', num: 4, club: '考纳斯' },
    { name: 'Kenny Rocha Santos', pos: 'DF', num: 2, club: '南锡' },
    { name: 'Lisandro Semedo', pos: 'FW', num: 7, club: '布加勒斯特快速' },
    { name: 'Garry Rodrigues', pos: 'FW', num: 10, club: '费内巴切' },
    { name: 'Ryan Mendes', pos: 'FW', num: 9, club: '阿兰亚斯堡' },
    { name: 'Jamiro Monteiro', pos: 'MF', num: 8, club: '加拉塔萨雷' },
    { name: 'Diney Borges', pos: 'DF', num: 3, club: 'AZ阿尔克马尔' },
  ]},
  '沙特阿拉伯': { coach: '埃尔韦·勒纳尔', players: [
    { name: 'Mohammed Al-Owais', pos: 'GK', num: 1, club: '利雅得新月' },
    { name: 'Sultan Al-Ghanam', pos: 'DF', num: 2, club: '利雅得胜利' },
    { name: 'Ali Al-Bulayhi', pos: 'DF', num: 5, club: '利雅得新月' },
    { name: 'Salman Al-Faraj', pos: 'MF', num: 7, club: '利雅得新月' },
    { name: 'Salem Al-Dawsari', pos: 'FW', num: 10, club: '利雅得新月' },
    { name: 'Firas Al-Buraikan', pos: 'FW', num: 9, club: '利雅得胜利' },
    { name: 'Abdulrahman Al-Aboud', pos: 'FW', num: 11, club: '吉达伊蒂哈德' },
    { name: 'Mohamed Kanno', pos: 'MF', num: 8, club: '利雅得新月' },
  ]},
  '乌拉圭': { coach: '马塞洛·贝尔萨', players: [
    { name: 'Sergio Rochet', pos: 'GK', num: 1, club: '国际米兰' },
    { name: 'Jose Maria Gimenez', pos: 'DF', num: 2, club: '马德里竞技' },
    { name: 'Ronald Araujo', pos: 'DF', num: 4, club: '巴塞罗那' },
    { name: 'Mathias Olivera', pos: 'DF', num: 16, club: '那不勒斯' },
    { name: 'Federico Valverde', pos: 'MF', num: 10, club: '皇家马德里' },
    { name: 'Rodrigo Bentancur', pos: 'MF', num: 8, club: '热刺' },
    { name: 'Nicolas De La Cruz', pos: 'MF', num: 6, club: '河床' },
    { name: 'Darwin Nunez', pos: 'FW', num: 9, club: '利物浦' },
    { name: 'Maxi Gomez', pos: 'FW', num: 11, club: '特拉布宗体育' },
    { name: 'Giorgian De Arrascaeta', pos: 'FW', num: 7, club: '弗拉门戈' },
  ]},
  '法国': { coach: '迪迪埃·德尚', players: [
    { name: 'Mike Maignan', pos: 'GK', num: 16, club: 'AC米兰' },
    { name: 'William Saliba', pos: 'DF', num: 17, club: '阿森纳' },
    { name: 'Dayot Upamecano', pos: 'DF', num: 4, club: '拜仁慕尼黑' },
    { name: 'Jules Kounde', pos: 'DF', num: 5, club: '巴塞罗那' },
    { name: 'Theo Hernandez', pos: 'DF', num: 19, club: '利雅得新月' },
    { name: 'Aurelien Tchouameni', pos: 'MF', num: 8, club: '皇家马德里' },
    { name: "N'Golo Kante", pos: 'MF', num: 13, club: '费内巴切' },
    { name: 'Kylian Mbappe', pos: 'FW', num: 10, club: '皇家马德里' },
    { name: 'Ousmane Dembele', pos: 'FW', num: 7, club: '巴黎圣日耳曼' },
    { name: 'Michael Olise', pos: 'FW', num: 11, club: '拜仁慕尼黑' },
    { name: 'Marcus Thuram', pos: 'FW', num: 9, club: '国际米兰' },
    { name: 'Desire Doue', pos: 'FW', num: 20, club: '巴黎圣日耳曼' },
  ]},
  '塞内加尔': { coach: '帕普·蒂亚', players: [
    { name: 'Edouard Mendy', pos: 'GK', num: 16, club: '吉达国民' },
    { name: 'Kalidou Koulibaly', pos: 'DF', num: 3, club: '利雅得新月' },
    { name: 'Moussa Niakhate', pos: 'DF', num: 19, club: '里昂' },
    { name: 'Idrissa Gueye', pos: 'MF', num: 5, club: '埃弗顿' },
    { name: 'Lamine Camara', pos: 'MF', num: 8, club: '摩纳哥' },
    { name: 'Pape Matar Sarr', pos: 'MF', num: 17, club: '热刺' },
    { name: 'Sadio Mane', pos: 'FW', num: 10, club: '利雅得胜利' },
    { name: 'Nicolas Jackson', pos: 'FW', num: 11, club: '切尔西' },
    { name: 'Ismaila Sarr', pos: 'FW', num: 18, club: '水晶宫' },
    { name: 'Habib Diarra', pos: 'MF', num: 21, club: '桑德兰' },
  ]},
  '挪威': { coach: '斯塔勒·索尔巴肯', players: [
    { name: 'Orjan Nyland', pos: 'GK', num: 1, club: '塞维利亚' },
    { name: 'Kristoffer Ajer', pos: 'DF', num: 3, club: '布伦特福德' },
    { name: 'Julian Ryerson', pos: 'DF', num: 26, club: '多特蒙德' },
    { name: 'Martin Odegaard', pos: 'MF', num: 10, club: '阿森纳' },
    { name: 'Sander Berge', pos: 'MF', num: 8, club: '富勒姆' },
    { name: 'Erling Haaland', pos: 'FW', num: 9, club: '曼城' },
    { name: 'Alexander Sorloth', pos: 'FW', num: 7, club: '马德里竞技' },
    { name: 'Antonio Nusa', pos: 'FW', num: 20, club: '莱比锡' },
    { name: 'Jorgen Strand Larsen', pos: 'FW', num: 11, club: '水晶宫' },
    { name: 'Oscar Bobb', pos: 'MF', num: 22, club: '曼城' },
  ]},
  '伊拉克': { coach: '格雷厄姆·阿诺德', players: [
    { name: 'Jalal Hassan', pos: 'GK', num: 12, club: '祖拉' },
    { name: 'Rebin Sulaka', pos: 'DF', num: 2, club: '波尔蒂芒人' },
    { name: 'Merchas Doski', pos: 'DF', num: 23, club: '比尔森胜利' },
    { name: 'Zidane Iqbal', pos: 'MF', num: 14, club: '乌得勒支' },
    { name: 'Ibrahim Bayesh', pos: 'MF', num: 8, club: '豪尔' },
    { name: 'Aymen Hussein', pos: 'FW', num: 18, club: '卡尔马' },
    { name: 'Mohanad Ali', pos: 'FW', num: 10, club: '迪巴' },
    { name: 'Ali Jasim', pos: 'FW', num: 17, club: '纳吉马' },
  ]},
  '阿根廷': { coach: '利昂内尔·斯卡洛尼', players: [
    { name: 'Emiliano Martinez', pos: 'GK', num: 23, club: '阿斯顿维拉' },
    { name: 'Cristian Romero', pos: 'DF', num: 13, club: '热刺' },
    { name: 'Lisandro Martinez', pos: 'DF', num: 6, club: '曼联' },
    { name: 'Nahuel Molina', pos: 'DF', num: 26, club: '马德里竞技' },
    { name: 'Rodrigo De Paul', pos: 'MF', num: 7, club: '迈阿密国际' },
    { name: 'Enzo Fernandez', pos: 'MF', num: 24, club: '切尔西' },
    { name: 'Alexis Mac Allister', pos: 'MF', num: 20, club: '利物浦' },
    { name: 'Lionel Messi', pos: 'FW', num: 10, club: '迈阿密国际' },
    { name: 'Julian Alvarez', pos: 'FW', num: 9, club: '马德里竞技' },
    { name: 'Lautaro Martinez', pos: 'FW', num: 22, club: '国际米兰' },
    { name: 'Thiago Almada', pos: 'FW', num: 16, club: '马德里竞技' },
  ]},
  '阿尔及利亚': { coach: '弗拉基米尔·佩特科维奇', players: [
    { name: 'Luca Zidane', pos: 'GK', num: 23, club: '格拉纳达' },
    { name: 'Rayan Ait-Nouri', pos: 'DF', num: 15, club: '曼城' },
    { name: 'Ramy Bensebaini', pos: 'DF', num: 21, club: '多特蒙德' },
    { name: 'Aissa Mandi', pos: 'DF', num: 2, club: '里尔' },
    { name: 'Houssem Aouar', pos: 'MF', num: 8, club: '吉达联合' },
    { name: 'Fares Chaibi', pos: 'MF', num: 10, club: '法兰克福' },
    { name: 'Riyad Mahrez', pos: 'FW', num: 7, club: '吉达国民' },
    { name: 'Mohamed Amoura', pos: 'FW', num: 18, club: '沃尔夫斯堡' },
    { name: 'Amine Gouiri', pos: 'FW', num: 9, club: '马赛' },
    { name: 'Ibrahim Maza', pos: 'MF', num: 22, club: '勒沃库森' },
  ]},
  '奥地利': { coach: '拉尔夫·朗尼克', players: [
    { name: 'Alexander Schlager', pos: 'GK', num: 1, club: '萨尔茨堡' },
    { name: 'David Alaba', pos: 'DF', num: 8, club: '皇家马德里' },
    { name: 'Kevin Danso', pos: 'DF', num: 3, club: '热刺' },
    { name: 'Marcel Sabitzer', pos: 'MF', num: 9, club: '多特蒙德' },
    { name: 'Konrad Laimer', pos: 'MF', num: 20, club: '拜仁慕尼黑' },
    { name: 'Xaver Schlager', pos: 'MF', num: 4, club: '莱比锡' },
    { name: 'Marko Arnautovic', pos: 'FW', num: 7, club: '贝尔格莱德红星' },
    { name: 'Michael Gregoritsch', pos: 'FW', num: 11, club: '奥格斯堡' },
    { name: 'Paul Wanner', pos: 'MF', num: 24, club: '埃因霍温' },
    { name: 'Philipp Lienhart', pos: 'DF', num: 15, club: '弗赖堡' },
  ]},
  '约旦': { coach: '贾马尔·塞拉米', players: [
    { name: 'Yazeed Abulaila', pos: 'GK', num: 1, club: '侯赛因' },
    { name: 'Ihsan Haddad', pos: 'DF', num: 23, club: '侯赛因' },
    { name: 'Yazan Al-Arab', pos: 'DF', num: 5, club: 'FC首尔' },
    { name: 'Noor Al-Rawabdeh', pos: 'MF', num: 8, club: '雪兰莪' },
    { name: 'Musa Al-Taamari', pos: 'FW', num: 10, club: '雷恩' },
    { name: 'Yazan Al-Naimat', pos: 'FW', num: 18, club: '阿尔阿拉比' },
    { name: 'Ali Olwan', pos: 'FW', num: 9, club: '赛利亚' },
    { name: 'Nizar Al-Rashdan', pos: 'MF', num: 21, club: '卡塔尔SC' },
  ]},
  '葡萄牙': { coach: '罗伯托·马丁内斯', players: [
    { name: 'Diogo Costa', pos: 'GK', num: 1, club: '波尔图' },
    { name: 'Ruben Dias', pos: 'DF', num: 3, club: '曼城' },
    { name: 'Diogo Dalot', pos: 'DF', num: 5, club: '曼联' },
    { name: 'Nuno Mendes', pos: 'DF', num: 25, club: '巴黎圣日耳曼' },
    { name: 'Bruno Fernandes', pos: 'MF', num: 8, club: '曼联' },
    { name: 'Bernardo Silva', pos: 'MF', num: 10, club: '曼城' },
    { name: 'Vitinha', pos: 'MF', num: 23, club: '巴黎圣日耳曼' },
    { name: 'Joao Neves', pos: 'MF', num: 15, club: '巴黎圣日耳曼' },
    { name: 'Cristiano Ronaldo', pos: 'FW', num: 7, club: '利雅得胜利' },
    { name: 'Rafael Leao', pos: 'FW', num: 17, club: 'AC米兰' },
    { name: 'Goncalo Ramos', pos: 'FW', num: 9, club: '巴黎圣日耳曼' },
    { name: 'Francisco Conceicao', pos: 'FW', num: 26, club: '尤文图斯' },
  ]},
  '民主刚果': { coach: '塞巴斯蒂安·德萨布尔', players: [
    { name: 'Lionel Mpasi', pos: 'GK', num: 1, club: '勒阿弗尔' },
    { name: 'Chancel Mbemba', pos: 'DF', num: 22, club: '里尔' },
    { name: 'Aaron Wan-Bissaka', pos: 'DF', num: 2, club: '西汉姆' },
    { name: 'Theo Bongonda', pos: 'MF', num: 10, club: '莫斯科斯巴达' },
    { name: 'Cedric Bakambu', pos: 'FW', num: 17, club: '皇家贝蒂斯' },
    { name: 'Fiston Mayele', pos: 'FW', num: 19, club: '金字塔' },
    { name: 'Yoane Wissa', pos: 'FW', num: 20, club: '纽卡斯尔' },
    { name: 'Meschak Elia', pos: 'FW', num: 13, club: '阿兰亚斯堡' },
  ]},
  '乌兹别克斯坦': { coach: '法比奥·卡纳瓦罗', players: [
    { name: 'Utkir Yusupov', pos: 'GK', num: 1, club: '纳巴霍尔' },
    { name: 'Abdukodir Khusanov', pos: 'DF', num: 2, club: '曼城' },
    { name: 'Rustam Ashurmatov', pos: 'DF', num: 5, club: '独立' },
    { name: 'Jaloliddin Masharipov', pos: 'MF', num: 10, club: '独立' },
    { name: 'Abbosbek Fayzullaev', pos: 'MF', num: 22, club: '伊斯坦布尔' },
    { name: 'Eldor Shomurodov', pos: 'FW', num: 14, club: '伊斯坦布尔' },
    { name: 'Igor Sergeev', pos: 'FW', num: 21, club: '波斯波利斯' },
    { name: 'Oston Urunov', pos: 'MF', num: 11, club: '波斯波利斯' },
  ]},
  '哥伦比亚': { coach: '内斯托尔·洛伦佐', players: [
    { name: 'David Ospina', pos: 'GK', num: 1, club: '麦德林国民竞技' },
    { name: 'Davinson Sanchez', pos: 'DF', num: 23, club: '加拉塔萨雷' },
    { name: 'Daniel Munoz', pos: 'DF', num: 2, club: '水晶宫' },
    { name: 'Jefferson Lerma', pos: 'MF', num: 16, club: '水晶宫' },
    { name: 'James Rodriguez', pos: 'MF', num: 10, club: '明尼苏达联' },
    { name: 'Richard Rios', pos: 'MF', num: 6, club: '本菲卡' },
    { name: 'Luis Diaz', pos: 'FW', num: 7, club: '拜仁慕尼黑' },
    { name: 'Jhon Arias', pos: 'MF', num: 11, club: '帕尔梅拉斯' },
    { name: 'Jhon Cordoba', pos: 'FW', num: 9, club: '克拉斯诺达尔' },
  ]},
  '英格兰': { coach: '托马斯·图赫尔', players: [
    { name: 'Jordan Pickford', pos: 'GK', num: 1, club: '埃弗顿' },
    { name: 'John Stones', pos: 'DF', num: 5, club: '曼城' },
    { name: 'Marc Guehi', pos: 'DF', num: 6, club: '曼城' },
    { name: 'Declan Rice', pos: 'MF', num: 4, club: '阿森纳' },
    { name: 'Jude Bellingham', pos: 'MF', num: 10, club: '皇家马德里' },
    { name: 'Elliot Anderson', pos: 'MF', num: 8, club: '诺丁汉森林' },
    { name: 'Harry Kane', pos: 'FW', num: 9, club: '拜仁慕尼黑' },
    { name: 'Bukayo Saka', pos: 'FW', num: 7, club: '阿森纳' },
    { name: 'Marcus Rashford', pos: 'FW', num: 11, club: '巴塞罗那' },
    { name: 'Morgan Rogers', pos: 'MF', num: 17, club: '阿斯顿维拉' },
    { name: 'Eberechi Eze', pos: 'MF', num: 21, club: '阿森纳' },
  ]},
  '克罗地亚': { coach: '兹拉特科·达利奇', players: [
    { name: 'Dominik Livakovic', pos: 'GK', num: 1, club: '萨格勒布迪纳摩' },
    { name: 'Josko Gvardiol', pos: 'DF', num: 4, club: '曼城' },
    { name: 'Josip Sutalo', pos: 'DF', num: 6, club: '阿贾克斯' },
    { name: 'Luka Modric', pos: 'MF', num: 10, club: 'AC米兰' },
    { name: 'Mateo Kovacic', pos: 'MF', num: 8, club: '曼城' },
    { name: 'Mario Pasalic', pos: 'MF', num: 15, club: '亚特兰大' },
    { name: 'Andrej Kramaric', pos: 'FW', num: 9, club: '霍芬海姆' },
    { name: 'Ante Budimir', pos: 'FW', num: 11, club: '奥萨苏纳' },
    { name: 'Ivan Perisic', pos: 'FW', num: 14, club: '埃因霍温' },
    { name: 'Josip Stanisic', pos: 'DF', num: 2, club: '拜仁慕尼黑' },
  ]},
  '加纳': { coach: '卡洛斯·奎罗兹', players: [
    { name: 'Lawrence Ati-Zigi', pos: 'GK', num: 1, club: '圣加仑' },
    { name: 'Alidu Seidu', pos: 'DF', num: 2, club: '雷恩' },
    { name: 'Abdul Mumin', pos: 'DF', num: 6, club: '巴列卡诺' },
    { name: 'Thomas Partey', pos: 'MF', num: 5, club: '比利亚雷亚尔' },
    { name: 'Antoine Semenyo', pos: 'MF', num: 11, club: '曼城' },
    { name: 'Inaki Williams', pos: 'FW', num: 19, club: '毕尔巴鄂竞技' },
    { name: 'Jordan Ayew', pos: 'FW', num: 9, club: '莱斯特城' },
    { name: 'Abdul Fatawu', pos: 'FW', num: 7, club: '莱斯特城' },
    { name: 'Kamaldeen Sulemana', pos: 'FW', num: 22, club: '亚特兰大' },
  ]},
  '巴拿马': { coach: '托马斯·克里斯蒂安森', players: [
    { name: 'Luis Mejia', pos: 'GK', num: 1, club: '国民' },
    { name: 'Michael Amir Murillo', pos: 'DF', num: 23, club: '贝西克塔斯' },
    { name: 'Eric Davis', pos: 'DF', num: 15, club: '广场阿马多尔' },
    { name: 'Adalberto Carrasquilla', pos: 'MF', num: 8, club: 'UNAM' },
    { name: 'Anibal Godoy', pos: 'MF', num: 20, club: '圣迭戈FC' },
    { name: 'Ismael Diaz', pos: 'FW', num: 10, club: '莱昂' },
    { name: 'Jose Fajardo', pos: 'FW', num: 17, club: '天主教大学' },
    { name: 'Cecilio Waterman', pos: 'FW', num: 18, club: '康塞普西翁' },
    { name: 'Yoel Barcenas', pos: 'MF', num: 11, club: '马萨特兰' },
  ]},
};
